export const BOOKING_STATUS = {
  BOOKED: "BOOKED",
  ASSIGNED: "ASSIGNED",
  PICKUP_STARTED: "PICKUP_STARTED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
  RESCHEDULED: "RESCHEDULED"
};